### ISSUE TITLE
戴森球计划, 疑似传送带bug

### ISSUE THREAD

**Issue by wqj97** [xiaoye97/xiaoye97-BepInex-Plugins#1]
![image](https://user-images.githubusercontent.com/18662395/107140797-7e7f1780-695f-11eb-92f4-8d512d78d387.png)

**Comment by wqj97** [comment]
只是看到CargoPath, 感觉是传送带Mod的问题

**Comment by xiaoye97** [comment]
这确实是传送带的bug，而且是MK2型特有的，目前来看，是因为速度太快，超过了游戏的物理帧，导致一帧时间移动了超过1个格子，在一些特定的时候会造成数据越界。不过不知道为什么我这里复现不出来，只有几个玩家触发出来给我反馈，所以暂时还没有特别好的修复方法，我还在研究这一部分的逻辑，等修好了会更新版本。你现在可以先用MK1型，那个没有什么问题。

**Comment by wqj97** [comment]
好的谢谢

**Comment by xiaoye97** [comment]
忘了这边还有个issues了，Bug已经修复，在网站上更新了，1.2.3之后的版本没有这个bug。

**Comment by wqj97** [comment]
好的
