### ISSUE TITLE
Issue with starting DSP with LDBTools plugin

### ISSUE THREAD

**Issue by Spock117** [xiaoye97/xiaoye97-BepInex-Plugins#2]
I tried to start DSP with the LDBTools plugin. I got this error:
![DSPGAME_ppJye3uPUB](https://user-images.githubusercontent.com/70015571/107297135-b316d000-6a40-11eb-8689-94728a19412f.png)
I've installed this using the mod manager r2modman. I do not know how to fix this. Please help!

**Comment by xiaoye97** [comment]
What version of LDBTool do you use? What other mods are installed? I need more details.

**Comment by Spock117** [comment]
It was fixed after today's update. I think it was an issue with DSP. 

This is the list of mods that were installed:
1. xiaoye97-BepInEx-5.4.5
2. xiaoye97-LDBTool-1.6.0
3. Alejandro1-BuildAnywhere-1.3.0
4. Zomatree-Discord_RPC-1.0.2
5. Windows10CE-IcarusColorPicker-1.1.0
6. sfwr-Forgetful-1.0.0
7. xiaoye97-SuperBelt-1.2.5
8. jinxOAO-WaterElectrolysis-1.0.2
9. HarriXS-More_Replication-1.1.0
10. pthcon-MorePlanets-1.2.0
11. HarriXS-More_Storage-0.1.2
12. markusmo3-SmolSplitters-1.0.0
13. pthcon-MegaSystems-1.2.1
14. Zorb-More_or_Less_Stars-1.0.0
